In [1]:
"1.导入numpy库并简写为 np"
import numpy as np

In [5]:
"2. 打印numpy的版本和配置说明"
print(np.__version__)
np.show_config()

1.15.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [6]:
"3.建立一个长度为10的空向量"
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
"4.如何找到任何一个数组的内存大小？"
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [8]:
"5.查看numpy中add函数的说明文档"
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [9]:
"6. 创建一个长度为10并且除了第五个值为1的空向量 "
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
"7. 创建一个值域范围从10到49的向量"
Z = np.arange(10,50)

In [11]:
"8. 反转一个向量(第一个元素变为最后一个)"
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [15]:
"9.创建一个 3x3 并且值从0到8的矩阵"
Z = np.arange(9).reshape(3,-1)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
"10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引"
nz = np.nonzero([1,2,3,0,0,1])
nz

(array([0, 1, 2, 5]),)

In [18]:
"11. 创建一个 3x3 的单位矩阵"
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
"12. 创建一个 3x3x3的随机数组"
Z = np.random.random((3,3,3))
Z

array([[[0.46371429, 0.5614426 , 0.24750799],
        [0.29536045, 0.71237404, 0.14615404],
        [0.03292942, 0.44387536, 0.26894495]],

       [[0.9115127 , 0.64016162, 0.21118853],
        [0.59627619, 0.62474167, 0.52295407],
        [0.74351203, 0.08354563, 0.88538193]],

       [[0.53252331, 0.97377772, 0.07690652],
        [0.42929931, 0.81576855, 0.86506525],
        [0.51589481, 0.21949793, 0.83441691]]])

In [20]:
"13. 创建一个 10x10 的随机数组并找到它的最大值和最小值"
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
Zmin
Zmax


0.9980971783831415

In [21]:
"14. 创建一个长度为30的随机向量并找到它的平均值"
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5500836786091355


In [24]:
"15. 创建一个二维数组，其中边界值为1，其余值为0"
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
"16. 对于一个存在在数组，如何添加一个用0填充的边界?"
Z = np.ones((5,5))
Z  = np.pad(Z, pad_width=1, mode='constant', constant_values = 0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [6]:
"17.以下表达式运行的结果分别是什么?"
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [52]:
"33. 如何得到昨天，今天，明天的日期?"
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-23
Today is 2019-06-24
Tomorrow is 2019-06-25


In [53]:
"34. 如何得到所有与2016年7月对应的日期？"
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [54]:
"35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)? "
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out = A)
np.multiply(A,B,out = A)


array([-1.5, -1.5, -1.5])

In [56]:
"36. 用五种不同的方法去提取一个随机数组的整数部分"
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[9. 4. 4. 1. 1. 3. 7. 6. 5. 6.]
[9. 4. 4. 1. 1. 3. 7. 6. 5. 6.]
[9. 4. 4. 1. 1. 3. 7. 6. 5. 6.]
[9 4 4 1 1 3 7 6 5 6]
[9. 4. 4. 1. 1. 3. 7. 6. 5. 6.]


In [57]:
"37. 创建一个5x5的矩阵，其中每行的数值范围从0到4"
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [61]:
"38. 通过考虑一个可生成10个整数的函数，来构建一个数组"
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [63]:
"39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1"
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [64]:
"40. 创建一个长度为10的随机向量，并将其排序"
Z = np.random.random(10)
Z.sort()

In [65]:
"41.对于一个小数组，如何用比 np.sum更快的方式对其求和？"
Z = np.arange(10)
np.add.reduce(Z)

45

In [69]:
"42. 对于两个随机数组A和B，检查它们是否相等"
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
equal = np.array_equal(A,B)

In [70]:
"43. 创建一个只读数组(read-only)"
Z = np.zeros(10)
Z.flags.writeable = False

In [72]:
"44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式"
Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)

In [74]:
"45. 创建一个长度为10的向量，并将向量中最大值替换为1"
Z = np.random.random(10)
Z[Z.argmax()] = 0
Z

array([0.57863139, 0.07406911, 0.46049213, 0.25788206, 0.51539642,
       0.        , 0.18392464, 0.46954357, 0.85209338, 0.68165401])

In [75]:
"46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 "
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [77]:
"47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))"
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [78]:
"48. 打印每个numpy标量类型的最小值和最大值？"
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [82]:
"49. 如何打印一个数组中的所有数值?"
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [84]:
"50. 给定标量时，如何找到数组中最接近标量的值"
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
index

25

In [85]:
"51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组"
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [88]:
"52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离"
Z = np.random.random((100,2))
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
D

array([[0.        , 0.34605386, 0.44606877, 0.6587114 , 0.68001245,
        0.12346033, 0.3243789 , 0.5265285 , 0.6644912 , 0.54600089,
        0.8203626 , 0.56757362, 0.24165296, 0.43963079, 0.53649974,
        0.72315442, 0.15378062, 0.56089157, 0.41137387, 0.31561602,
        0.16152699, 0.72546925, 0.54862344, 0.59630975, 0.46741662,
        0.46026779, 0.2569755 , 0.70568815, 0.14807466, 0.42141039,
        0.42220191, 0.20838329, 0.44783349, 0.16857867, 0.1869453 ,
        0.66746387, 0.53365677, 0.79738122, 0.25038573, 0.2250476 ,
        0.2839882 , 0.47866264, 0.92465966, 0.13167835, 0.43127974,
        0.45209337, 0.24325911, 0.53841312, 0.72265519, 0.70550933,
        0.26124818, 0.35076541, 0.60218094, 0.75828558, 0.43449114,
        0.43717656, 0.65255194, 0.25939421, 0.1050853 , 0.90105291,
        0.25115167, 0.72059191, 0.30963634, 0.21072153, 0.536154  ,
        0.35909175, 0.71579459, 0.74719968, 0.0932036 , 0.38112586,
        0.43575182, 0.74324517, 0.32809255, 0.44

In [89]:
"53. 如何将32位的浮点数(float)转换为对应的整数(integer)?"
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32,copy = False)

In [90]:
"55. 对于numpy数组，enumerate的等价操作是什么？"
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [91]:
"56. 生成一个通用的二维Gaussian-like数组"
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [92]:
"57. 对一个二维数组，如何在其内部随机放置p个元素?"
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [96]:
"58. 减去一个矩阵中的每一行的平均值"
X = np.random.rand(5,10)
Y = X - X.mean(axis=1,keepdims=True)

In [98]:
"59. 如何通过第n列对一个数组进行排序?"
Z = np.random.randint(0,10,(3,3))
print (Z[Z[:,1].argsort()])

[[6 6 7]
 [3 7 6]
 [0 8 2]]


In [99]:
"60. 如何检查一个二维数组是否有空列"
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())


False


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])