In [4]:
"1.导入numpy库并简写为 np"
import numpy as np

In [5]:
"2. 打印numpy的版本和配置说明"
print(np.__version__)
np.show_config()

1.15.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [6]:
"3.建立一个长度为10的空向量"
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
"4.如何找到任何一个数组的内存大小？"
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [8]:
"5.查看numpy中add函数的说明文档"
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [9]:
"6. 创建一个长度为10并且除了第五个值为1的空向量 "
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
"7. 创建一个值域范围从10到49的向量"
Z = np.arange(10,50)

In [11]:
"8. 反转一个向量(第一个元素变为最后一个)"
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [15]:
"9.创建一个 3x3 并且值从0到8的矩阵"
Z = np.arange(9).reshape(3,-1)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
"10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引"
nz = np.nonzero([1,2,3,0,0,1])
nz

(array([0, 1, 2, 5]),)

In [18]:
"11. 创建一个 3x3 的单位矩阵"
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
"12. 创建一个 3x3x3的随机数组"
Z = np.random.random((3,3,3))
Z

array([[[0.46371429, 0.5614426 , 0.24750799],
        [0.29536045, 0.71237404, 0.14615404],
        [0.03292942, 0.44387536, 0.26894495]],

       [[0.9115127 , 0.64016162, 0.21118853],
        [0.59627619, 0.62474167, 0.52295407],
        [0.74351203, 0.08354563, 0.88538193]],

       [[0.53252331, 0.97377772, 0.07690652],
        [0.42929931, 0.81576855, 0.86506525],
        [0.51589481, 0.21949793, 0.83441691]]])

In [20]:
"13. 创建一个 10x10 的随机数组并找到它的最大值和最小值"
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
Zmin
Zmax


0.9980971783831415

In [21]:
"14. 创建一个长度为30的随机向量并找到它的平均值"
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5500836786091355


In [23]:
"15. 创建一个二维数组，其中边界值为1，其余值为0"
Z = np.ones((10,10))
Z[1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])